version: '3'

services:

  api:
    container_name: freela_api
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - api-network

  mongodb:
    image: mongo
    container_name: freela_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data
    networks:
      - api-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwdlocal

networks:
  api-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local